[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[server]
maxUploadSize = 1000
enableCORS = false

[runner]
magicEnabled = true

[browser]
gatherUsageStats = false
